### ISSUE TITLE
5v signal on JP3 pins 2&4

### ISSUE THREAD

**Issue by blurfl** [ldocull/MaslowDue#2]
Looking at the schematic, I wonder whether the two pins on JP3 that are used to indicate the board version should be fed by 3v3 instead of 5v. I haven't hooked a Due up to a Maslow board, but the Arduino Due datasheets warn about damage from connecting 5v to the input pins. Have you found that it doesn't matter?
 Studying further, it doesn't seem that the board version ID is used. If that is so, then those pins don't matter. It would also mean that the GND on JP4-1&3 could be removed, making the hardware SCL and SDA available for the EEPROM.

**Comment by ldocull** [comment]
Good catch! I didn't experience any issue, but will update the schematic to reflect.  Those pins could be clipped off since they are not used. It would be cool to move the I2C to the hardware pins in future revs, although the accesses to EEPROM are few and far between, so not overly speed critical.    Thanks!

**Comment by ldocull** [comment]
Updated data and notes posted. Thanks for your input!

**Comment by aluminumwelder** [comment]
Thanks for doing this so fast. So do the pins need to still be clipped off? or are the gerber files now updated so no pins need to be clipped off?

**Comment by ldocull** [comment]
Gerbers upload today have this adjustment.
Thanks,
Larry
